# Generated by Django 4.2.7 on 2024-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_tokenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmodel',
            name='token',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
