# Generated by Django 4.2.7 on 2024-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
